### PR TITLE
Adding "Wings over the Golden Gate" from the 1930s

### PR DESCRIPTION
**Pull request by prestonrhea**
A nice video of color aerial footage of the SF Bay in the 1930s.

### CODE REVIEW

**Comment by migurski** [comment]
The video’s ten minutes long, but this will switch away after 2min. Is there a particular short part of the video we should jump to?

**Comment by migurski** [comment]
We could also play the full ten, but that seems rude. :)

**Comment by prestonrhea** [comment]
I think if you start it at 0:25 and let it play until 3:23, that's the best portion. Review that section and lmk what you think :)

**Comment by migurski** [comment]
Done and done.

**Comment by prestonrhea** [comment]
Your city thanks you!

On Mon, Jul 28, 2014 at 10:22 PM, migurski notifications@github.com wrote:

> Done and done.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/office-screen/pull/15#issuecomment-50435603
> .

## 

Preston Rhea
Brigade Program Coordinator
Code for America
+1-202-570-9770
@prestonrhea

**Pull request merged**
